FROM node:16-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install -g cross-env

COPY . .

ENV DISABLE_ESLINT_PLUGIN=true
ENV CI=false
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]